SET SERVEROUTPUT ON
DECLARE
    v_dob DATE := TO_DATE('1980-01-01', 'YYYY-MM-DD');
    v_age NUMBER;
BEGIN
    v_age := TRUNC(MONTHS_BETWEEN(SYSDATE, v_dob) / 12);
    DBMS_OUTPUT.PUT_LINE('Age: ' || v_age);
END;
/
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE('1980-01-01', 'YYYY-MM-DD')) / 12) AS AGE FROM dual;
